--- 
- 
  become: true
  hosts: localhost
  roles: 
    - LAMP
    - wordpress_configure
    - mysql
  vars: 
    ansible_python_interpreter: /usr/bin/python3
    wp_mysql_db: wordpress
    wp_mysql_host: localhost
    wp_mysql_password: password123
    wp_mysql_user: wp-admin